spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spreader?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: test1234!@
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
redis:
  host: localhost
  port: 6379
